import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { type SqlDialect, SqlMerger } from '../src/sql-merger.js';
import {
	DependencyError,
	ErrorCode,
	type SqlMergerError,
} from '../src/types/errors.js';

const fixture = (dialect: SqlDialect, scenario: string): string =>
	resolve(process.cwd(), `test/fixtures/${dialect}/${scenario}`);

const mergeScenario = (
	dialect: SqlDialect,
	scenario: string,
	merger = new SqlMerger(),
): string => {
	const files = merger.parseSqlFiles(fixture(dialect, scenario), dialect);
	return merger.mergeFiles(files, {
		addComments: false,
		includeHeader: false,
	});
};

/**
 * Statement-level merge contract: the output is ordered by statement (not by
 * file), nothing from the input files is lost, and dependencies always come
 * before their dependents in the emitted SQL.
 */
describe('statement-level merging', () => {
	describe('interleaved cross-file dependencies', () => {
		const dialects: SqlDialect[] = ['postgresql', 'sqlite'];

		dialects.forEach((dialect) => {
			it(`emits statements in dependency order even when files interleave (${dialect})`, () => {
				// a.sql: x (no deps), z -> y; b.sql: y -> x. Correct order: x, y, z.
				const merged = mergeScenario(
					dialect,
					'correct/interleaved_dependencies',
				);

				const posX = merged.indexOf('CREATE TABLE x');
				const posY = merged.indexOf('CREATE TABLE y');
				const posZ = merged.indexOf('CREATE TABLE z');

				expect(posX).toBeGreaterThanOrEqual(0);
				expect(posY).toBeGreaterThanOrEqual(0);
				expect(posZ).toBeGreaterThanOrEqual(0);
				expect(posX).toBeLessThan(posY);
				expect(posY).toBeLessThan(posZ);
			});
		});
	});

	describe('unrecognized (raw) statements', () => {
		it('keeps every raw statement in the output exactly once', () => {
			const merged = mergeScenario('postgresql', 'correct/raw_statements');

			for (const snippet of [
				'CREATE INDEX idx_users_name',
				'ALTER TABLE users ADD COLUMN age',
				"INSERT INTO users (name) VALUES ('admin')",
				'INSERT INTO audit (user_id) VALUES (1)',
			]) {
				const first = merged.indexOf(snippet);
				expect(first, `missing: ${snippet}`).toBeGreaterThanOrEqual(0);
				expect(
					merged.indexOf(snippet, first + 1),
					`duplicated: ${snippet}`,
				).toBe(-1);
			}
		});

		it('emits raw statements after the recognized statement they follow in their file', () => {
			const merged = mergeScenario('postgresql', 'correct/raw_statements');

			const posUsers = merged.indexOf('CREATE TABLE users');
			const posAudit = merged.indexOf('CREATE TABLE audit');
			const posIndex = merged.indexOf('CREATE INDEX idx_users_name');
			const posAlter = merged.indexOf('ALTER TABLE users ADD COLUMN age');
			const posInsertUsers = merged.indexOf('INSERT INTO users');
			const posInsertAudit = merged.indexOf('INSERT INTO audit');

			// topological order of the tables themselves
			expect(posUsers).toBeLessThan(posAudit);
			// raw statements stay behind their anchor table
			expect(posIndex).toBeGreaterThan(posUsers);
			expect(posAlter).toBeGreaterThan(posUsers);
			expect(posInsertUsers).toBeGreaterThan(posUsers);
			expect(posInsertAudit).toBeGreaterThan(posAudit);
			// audit's INSERT must not ride along with users' raw block
			expect(posInsertAudit).toBeGreaterThan(posInsertUsers);
		});
	});

	describe('IDENTITY normalization is parse-only', () => {
		it('keeps GENERATED ... AS IDENTITY clauses verbatim in the output', () => {
			const merged = mergeScenario('postgresql', 'correct/identity_columns');

			expect(merged).toContain('GENERATED ALWAYS AS IDENTITY');
			expect(merged).toContain(
				'GENERATED BY DEFAULT AS IDENTITY (START WITH 100)',
			);
			// dependency order still applies
			expect(merged.indexOf('CREATE TABLE accounts')).toBeLessThan(
				merged.indexOf('CREATE TABLE sessions'),
			);
		});
	});

	describe('comments travel with their statements', () => {
		it('moves a leading comment together with its statement on reorder', () => {
			// Files sort as a_child.sql, z_parent.sql but parent must be emitted first.
			const merged = mergeScenario('postgresql', 'correct/comments_travel');

			const posParentComment = merged.indexOf('-- Parent table comment');
			const posParent = merged.indexOf('CREATE TABLE parent');
			const posChildComment = merged.indexOf(
				'-- Child table, references parent',
			);
			const posChild = merged.indexOf('CREATE TABLE child');

			expect(posParentComment).toBeGreaterThanOrEqual(0);
			expect(posChildComment).toBeGreaterThanOrEqual(0);
			expect(posParentComment).toBeLessThan(posParent);
			expect(posParent).toBeLessThan(posChildComment);
			expect(posChildComment).toBeLessThan(posChild);
		});
	});

	describe('generated per-statement comments', () => {
		it('labels each emitted statement with its source file', () => {
			const merger = new SqlMerger();
			const files = merger.parseSqlFiles(
				fixture('postgresql', 'correct/interleaved_dependencies'),
				'postgresql',
			);
			const merged = merger.mergeFiles(files); // addComments defaults to true

			const posY = merged.indexOf('CREATE TABLE y');
			const posZ = merged.indexOf('CREATE TABLE z');

			// z comes from a.sql and is emitted after y — its source label must
			// appear between y and z, not only once at the top of the output.
			const zSourceLabel = merged.lastIndexOf('a.sql', posZ);
			expect(zSourceLabel).toBeGreaterThan(posY);
		});
	});

	describe('dependency extraction', () => {
		it('reports each dependency once, even when declared as a table-level constraint', () => {
			const merger = new SqlMerger();
			const file = merger.parseSingleFile(
				resolve(
					process.cwd(),
					'test/fixtures/postgresql/correct/interleaved_dependencies/b.sql',
				),
				'postgresql',
			);

			expect(file.statements).toHaveLength(1);
			expect(file.statements[0].dependsOn.map((d) => d.name)).toEqual(['x']);
		});
	});

	describe('missing dependencies', () => {
		const missingDepPath = fixture('postgresql', 'invalid/missing_dependency');

		it('throws MISSING_DEPENDENCY when a FK references an unknown table', () => {
			const merger = new SqlMerger();

			try {
				merger.parseSqlFiles(missingDepPath, 'postgresql');
				expect.fail('expected parseSqlFiles to throw');
			} catch (error) {
				expect(error).toBeInstanceOf(DependencyError);
				expect((error as SqlMergerError).code).toBe(
					ErrorCode.MISSING_DEPENDENCY,
				);
			}
		});

		it('merges anyway when allowExternalReferences is enabled', () => {
			const merger = new SqlMerger({ allowExternalReferences: true });

			const files = merger.parseSqlFiles(missingDepPath, 'postgresql');
			const merged = merger.mergeFiles(files, {
				addComments: false,
				includeHeader: false,
			});

			expect(merged).toContain('CREATE TABLE orders');
			expect(merged).toContain('REFERENCES customers(id)');
		});
	});

	describe('source order validation option', () => {
		const badOrderPath = fixture('postgresql', 'invalid/bad_statement_order');

		it('rejects out-of-order statements within a file by default', () => {
			const merger = new SqlMerger();

			expect(() => merger.parseSqlFiles(badOrderPath, 'postgresql')).toThrow(
				'Invalid statement order',
			);
		});

		it('merges out-of-order files correctly when validateSourceOrder is false', () => {
			const merger = new SqlMerger({ validateSourceOrder: false });

			const files = merger.parseSqlFiles(badOrderPath, 'postgresql');
			const merged = merger.mergeFiles(files, {
				addComments: false,
				includeHeader: false,
			});

			expect(merged.indexOf('CREATE TABLE countries')).toBeLessThan(
				merged.indexOf('CREATE TABLE cities'),
			);
		});
	});
});
